---
- name: "ZFS Performance Test with FIO"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    test_device: "/dev/sda5"
    test_device_short: "hdd"
    test_mount_point: "/mnt/test"
    filesystem_type: "zfs" 
    test_device: >-
      {{ 
        ("/dev/sda5" if test_device_short == "hdd" else
         "/dev/sdb1" if test_device_short == "ssd" else
         "/dev/nvme0n1p4" if test_device_short == "nvme" else
         fail("Invalid test_device_short value: " ~ test_device_short)) | trim 
      }}

    dd_results_path: "./wyniki/dd_results_{{ filesystem_type }}_{{ test_device_short }}/"
    fio_results_path: "./wyniki/fio_results_{{ filesystem_type }}_{{ test_device_short }}/"
    hdparm_results_path: "./wyniki/hdparm_results_{{ filesystem_type }}_{{ test_device_short }}/"
  vars_files:
    - ./fio/fio_configs_vars.yaml
    - ./dd/dd_vars.yaml
    
  tasks:
    
    - name: Usuń system plików ZFS
      block:
        - name: Odmontuj system plików ZFS
          command: zfs unmount mypool/myfilesystem
          ignore_errors: true

        - name: Usuń system plików ZFS
          command: zfs destroy mypool/myfilesystem
          ignore_errors: true

        - name: Usuń pulę ZFS
          command: zpool destroy mypool
          ignore_errors: true
    
    - import_tasks: ./hdparm/hdparm_tests.yaml

    - import_tasks: prepare_tasks.yaml

    - name: Utwórz pulę ZFS na /dev/sda5
      command: zpool create mypool {{ test_device }}
      args:
        creates: /mypool

    - name: Utwórz system plików ZFS w puli
      command: zfs create mypool/myfilesystem
      args:
        creates: /mypool/myfilesystem

    - name: Ustaw punkt montowania systemu plików ZFS
      command: zfs set mountpoint={{ test_mount_point }} mypool/myfilesystem
    
    - name: Mount DVD read-only
      ansible.posix.mount:
        path: "{{ test_mount_point }}"
        src: "{{ test_device }}"
        fstype: zfs
        opts: "defaults,noatime"
        state: mounted

    - import_tasks: ./dd/dd_tests.yaml
    
    - import_tasks: ./fio/fio_run.yaml

    - name: Usuń system plików ZFS
      block:
        - name: Odmontuj system plików ZFS
          command: zfs unmount mypool/myfilesystem
          ignore_errors: true

        - name: Usuń system plików ZFS
          command: zfs destroy mypool/myfilesystem
          ignore_errors: true

        - name: Usuń pulę ZFS
          command: zpool destroy mypool
          ignore_errors: true




