---
- name: Run dd test
  ansible.builtin.shell: >
    dd if={{ item.if }} of={{ item.of }} bs={{ item.bs }} count={{ item.count }}
    {% if item.iflag is defined %}iflag={{ item.iflag }}{% endif %}
    {% if item.oflag is defined %}oflag={{ item.oflag }}{% endif %}
  register: dd_result
  loop: "{{ dd_tests }}"
  loop_control:
    label: "{{ item.name }}"

#- debug: var=dd_result.stdout_lines
#- debug: var=dd_result.results
#- debug: var=dd_tests

- name: Save dd test result
  vars:
    results: "{{ dd_result.results }}"
  ansible.builtin.copy:
    content: |
      {{ item.stderr | default('No stderr captured') }}
    dest: "/tmp/{{ item.item.name }}_output.txt"
  loop: "{{ results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Clean up contents of the test directory
  ansible.builtin.shell: "rm -r {{ test_mount_point }}/*"

- name: Fetch dd test results
  ansible.builtin.fetch:
    src: "/tmp/{{ item.name }}_output.txt"
    dest: "{{ dd_results_path }}"
    flat: yes
  loop: "{{ dd_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Save DD configuration to results folder
  ansible.builtin.copy:
    content: |
      {% for test in dd_tests %}
      Test Name: {{ test.name }}
      Block Size: {{ test.bs }}
      Count: {{ test.count }}
      Input File: {{ test.if | default('N/A') }}
      Output File: {{ test.of | default('N/A') }}
      Input Flags: {{ test.iflag | default('N/A') }}
      Output Flags: {{ test.oflag | default('N/A') }}
      {% endfor %}
    dest: "/tmp/dd_config.txt"

- name: Fetch hdparm configuration file
  ansible.builtin.fetch:
    src: "/tmp/dd_config.txt"
    dest: "{{ dd_results_path }}/dd_config.txt"
    flat: yes