---
- name: Create FIO config files
  ansible.builtin.copy:
    dest: "/tmp/fio_{{ item.name }}.fio"
    content: |
      [global]
      ioengine=libaio
      direct=1
      group_reporting
      directory={{ test_mount_point }}

      [{{ item.name }}]
      rw={{ item.rw }}
      {% if item.rwmixread is defined %}rwmixread={{ item.rwmixread }}
      {% endif %}
      size={{ item.size }}
      numjobs={{ item.numjobs }}
      {% if item.runtime is defined %}runtime={{ item.runtime }}
      {% endif %}
      iodepth={{ item.iodepth }}
      bssplit={{ item.bssplit }}
      {% if item.stonewall is defined and item.stonewall %}stonewall;
      {% endif %}
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"