---
- import_tasks: fio_configs.yaml

- name: Run FIO tests and clean up after each test
  ansible.builtin.shell: >
    fio /tmp/fio_{{ item.name }}.fio --output /tmp/fio_{{ item.name }}_output.txt &&
    rm -r {{ test_mount_point }}/*
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Gather FIO results
  ansible.builtin.fetch:
    src: "/tmp/fio_{{ item.name }}_output.txt"
    dest: "{{ fio_results_path }}/{{ inventory_hostname }}/"
    flat: yes
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Save FIO configuration to results folder on remote machine
  ansible.builtin.copy:
    content: |
      Test Device: {{ test_device }}
      Test Mount Point: {{ test_mount_point }}
      Filesystem Type: ext4

      {% for test in fio_tests %}
      {{ test.name | capitalize }} Test:
        RW: {{ test.rw }}
        {% if test.rwmixread is defined %}RWMixRead: {{ test.rwmixread }}{% endif %}
        NumJobs: {{ test.numjobs }}
        {% if test.runtime is defined %}Runtime: {{ test.runtime }}{% endif %}
        Runtime: {{ test.runtime }}
        {% if test.iodepth is defined %}IOdepth: {{ test.iodepth }}{% endif %}
        BSSplit: {{ test.bssplit }}
        {% if test.stonewall is defined %}stonewall: {{ test.stonewall }}{% endif %}
        {% if test.time_based is defined %}time_based: {{ test.time_based }}{% endif %}
      {% endfor %}
    dest: "/tmp/fio_config.txt"

- name: Fetch FIO configuration file
  ansible.builtin.fetch:
    src: "/tmp/fio_config.txt"
    dest: "{{ fio_results_path }}/fio_config.txt"
    flat: yes