---
- import_tasks: fio_configs.yaml

- name: Install btrfs-compsize
  ansible.builtin.apt:
    name: btrfs-compsize
    state: present
  when: ansible_os_family == "Debian" and filesystem_type == "btrfs" and compression_option != "none"

- name: Run FIO tests, check files, and clean up after each test
  include_tasks: fio_single_test.yaml
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Save FIO configuration to results folder on remote machine
  ansible.builtin.copy:
    content: |
      Test Device: {{ test_device }}
      Test Mount Point: {{ test_mount_point }}
      Filesystem Type: {{ filesystem_type }}

      {% for test in fio_tests %}
      {{ test.name | capitalize }} Test:
        RW: {{ test.rw }}
        {% if test.rwmixread is defined %}RWMixRead: {{ test.rwmixread }}{% endif %}
        NumJobs: {{ test.numjobs }}
        {% if test.runtime is defined %}Runtime: {{ test.runtime }}{% endif %}
        Runtime: {{ test.runtime }}
        {% if test.iodepth is defined %}IOdepth: {{ test.iodepth }}{% endif %}
        {% if test.bssplit is defined %}BSSplit: {{ test.bssplit }}{% endif %}
        {% if test.stonewall is defined %}stonewall: {{ test.stonewall }}{% endif %}
        {% if test.time_based is defined %}time_based: {{ test.time_based }}{% endif %}
        {% if item.recordsize is defined %}recordsize={{ item.recordsize }}
        {% endif %}
        repeat={{ item.repeat | default(1) if filesystem_type in ["zfs", "zfs_l2arc"] else 1 }}  
        {% if compression_option != "none" %}
        buffer_compress_percentage=70
        refill_buffers
        buffer_pattern=0xdeadbeef
        {% endif %}
        {% if test.snapshot_count is defined and test.snapshot_count > 0 %}
        Snapshot Count: {{ test.snapshot_count }}
        {% endif %}
      {% endfor %}
    dest: "/tmp/fio_config.txt"

- name: Fetch FIO configuration file
  ansible.builtin.fetch:
    src: "/tmp/fio_config.txt"
    dest: "{{ fio_results_path }}/fio_config.txt"
    flat: yes