---
- import_tasks: fio_configs.yaml

- name: Run FIO tests and clean up after each test
  ansible.builtin.shell: >
    fio /tmp/fio_{{ item.name }}.fio --output /tmp/fio_{{ item.name }}_output.txt &&
    rm -r {{ test_mount_point }}/*
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"