---
- import_tasks: fio_configs.yaml
      
- name: Clear Linux caches (PageCache, dentries, inodes) before test
  ansible.builtin.shell: "echo 3 > /proc/sys/vm/drop_caches"
  changed_when: false
  when: clear_caches is defined and clear_caches

- name: Run FIO tests, check files, and clean up after each test
  include_tasks: fio_single_test.yaml
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Gather FIO results
  ansible.builtin.fetch:
    src: "/tmp/fio_{{ item.name }}_output.json"
    dest: "{{ fio_results_path }}/{{ inventory_hostname }}/"
    flat: yes
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Fetch file results to local results directory
  ansible.builtin.fetch:
    src: "/tmp/file_results_{{ item.name }}.json"
    dest: "{{ fio_results_path }}/{{ inventory_hostname }}/"
    flat: yes
  when: compression_option != "none"
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Fetch ARC stats file to local machine
  ansible.builtin.fetch:
    src:  "/tmp/arcstats_{{ item.name }}.log"
    dest: "{{ fio_results_path }}/{{ inventory_hostname }}/"
    flat: yes
  when: filesystem_type in ["zfs", "zfs_l2arc"]
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"

- name: Save FIO configuration to results folder on remote machine
  ansible.builtin.copy:
    content: |
      Test Device: {{ test_device }}
      Test Mount Point: {{ test_mount_point }}
      Filesystem Type: {{ filesystem_type }}

      {% for test in fio_tests %}
      {{ test.name | capitalize }} Test:
        RW: {{ test.rw }}
        {% if test.rwmixread is defined %}RWMixRead: {{ test.rwmixread }}{% endif %}
        NumJobs: {{ test.numjobs }}
        {% if test.runtime is defined %}Runtime: {{ test.runtime }}{% endif %}
        Runtime: {{ test.runtime }}
        {% if test.iodepth is defined %}IOdepth: {{ test.iodepth }}{% endif %}
        {% if test.bssplit is defined %}BSSplit: {{ test.bssplit }}{% endif %}
        {% if test.stonewall is defined %}stonewall: {{ test.stonewall }}{% endif %}
        {% if test.time_based is defined %}time_based: {{ test.time_based }}{% endif %}
        {% if item.recordsize is defined %}recordsize={{ item.recordsize }}
        {% endif %}
        repeat={{ item.repeat | default(1) if filesystem_type in ["zfs", "zfs_l2arc"] else 1 }}  
        {% if compression_option != "none" %}
        buffer_compress_percentage=70
        refill_buffers
        buffer_pattern=0xdeadbeef
        {% endif %}

      {% endfor %}
    dest: "/tmp/fio_config.txt"

- name: Fetch FIO configuration file
  ansible.builtin.fetch:
    src: "/tmp/fio_config.txt"
    dest: "{{ fio_results_path }}/fio_config.txt"
    flat: yes