---
- name: Run snapshot tests (short randwrite) for current batch
  include_tasks: fio_snapshot_test.yaml
  loop: "{{ snapshot_batch }}"
  loop_control:
    loop_var: repeat_index


- name: Run FIO test for snapshot batch
  ansible.builtin.shell: >
    fio /tmp/fio_{{ item.name }}.fio
    --output /tmp/fio_{{ item.name }}_output_snapshots_{{ snapshot_batch_name }}.json
    --output-format=json
  register: fio_result_batch
  changed_when: false
  failed_when: fio_result_batch.rc != 0
  with_sequence: >
    start=1
    end={{ item.repeat | default(1) if filesystem_type in ["zfs", "zfs_l2arc"] else 1 }}
  loop_control:
    loop_var: repeat_index
