---
- name: Create FIO config files
  ansible.builtin.copy:
    dest: "/tmp/fio_{{ item.name }}.fio"
    content: |
      [global]
      ioengine=libaio
      direct={{ direct_mode }}
      group_reporting
      directory={{ test_mount_point }}
      {% if compression_option != "none" %}
      buffer_compress_percentage=70
      refill_buffers
      buffer_pattern=0xdeadbeef
      {% endif %}

      [{{ item.name }}]
      rw={{ item.rw }}
      {% if item.rwmixread is defined %}rwmixread={{ item.rwmixread }}
      {% endif %}
      size={{ item.size }}
      numjobs={{ item.numjobs }}
      {% if item.runtime is defined %}runtime={{ item.runtime }}
      {% endif %}
      {% if item.iodepth is defined %}iodepth={{ item.iodepth }}
      {% endif %}
      {% if item.bssplit is defined %}bssplit={{ item.bssplit }}
      {% endif %}
      {% if item.stonewall is defined and item.stonewall %}stonewall;
      {% endif %}
      {% if item.time_based is defined and item.time_based %}time_based;
      {% endif %}
      {% if item.cpus_allowed_policy is defined %}cpus_allowed_policy={{ item.cpus_allowed_policy }}
      {% endif %}
  
  loop: "{{ fio_tests }}"
  loop_control:
    label: "{{ item.name }}"