---
- name: Run snapshot tests (short randwrite) for current batch
  include_tasks: fio_snapshot_test.yaml
  loop: "{{ snapshot_batch }}"
  loop_control:
    loop_var: repeat_index


- name: Run FIO test for snapshot batch
  ansible.builtin.shell: >
    fio /tmp/fio_{{ item.name }}.fio --output /tmp/fio_{{ item.name }}_output_snapshots_{{ snapshot_batch_name }}.json --output-format=json
  register: fio_result_batch
  changed_when: false
  failed_when: fio_result_batch.rc != 0

- name: Fetch all FIO per-batch output files
  ansible.builtin.fetch:
    src: "/tmp/fio_{{ item.name }}_output_snapshots_{{ snapshot_batch_name }}.json"
    dest: "{{ fio_results_path }}/{{ inventory_hostname }}/"
    flat: yes
