---
- name: "F2FS Performance Test with FIO"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    test_device: "/dev/sda5"
    test_device_short: "hdd"
    test_mount_point: "/mnt/test"
    filesystem_type: "f2fs" 

    dd_results_path: "./wyniki/dd_results_{{ filesystem_type }}_{{ test_device_short }}/"
    fio_results_path: "./wyniki/fio_results_{{ filesystem_type }}_{{ test_device_short }}/"
    hdparm_results_path: "./wyniki/hdparm_results_{{ filesystem_type }}_{{ test_device_short }}/"

  vars_files:
    - ./fio/fio_configs_vars.yaml
    - ./dd/dd_vars.yaml

  tasks:
    - import_tasks: ./hdparm/hdparm_tests.yaml
      
    - import_tasks: prepare_tasks.yaml

    - name: Create F2FS filesystem with specified block size
      community.general.filesystem:
        fstype: f2fs
        dev: "{{ test_device }}"

    - name: Mount the device to the test mount point
      ansible.posix.mount:
        path: "{{ test_mount_point }}"
        src: "{{ test_device }}"
        fstype: f2fs
        opts: "defaults,noatime"
        state: mounted

    - import_tasks: ./dd/dd_tests.yaml

    - import_tasks: fio_run.yaml

