---
- name: "Filesystem Performance Tests"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    enabled_programs:
      - fio
      - hdparm
      - dd
      - sysbench
    filesystems_to_test:
      - name: "ext4"
        block_sizes: [1024,2048] #możliwe wartości: ["default",1024,2048,4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "xfs"
        block_sizes: [1024,2048]  #możliwe wartości: ["default",1024,2048,4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "btrfs"
        block_sizes: [8192,16384,32768,65536]  #możliwe wartości: ["default",4096,8192,16384,32768,65536]
        mount_opts: "defaults,noatime"
        #compression_options: ["zstd", "lzo", "none"] #możliwe wartości: ["zstd", "lzo", "zlib", "none"]
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "f2fs"
        block_sizes: ["default"] 
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "zfs"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        compression_options: ["lz4"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        l2arc_device_short: "ssd"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: false
      - name: "zfs_nocache"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        compression_options: ["lz4"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "zfs_primary"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        compression_options: ["lz4"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "exfat"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
    test_mount_point: "/mnt/test"
    results_base_path: "./wyniki"
  vars_files:
    - ./fio/fio_configs_vars.yaml
    - ./dd/dd_vars.yaml
    - ./sysbench/sysbench_configs_vars.yaml

  tasks:
    - name: Run tests for each filesystem and device
      include_tasks: perform_filesystem_tests.yaml
      loop: "{{ filesystems_to_test | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: filesystem
      vars:
        block_sizes: "{{ filesystem.block_sizes | default(['default']) }}"
        compression_options: "{{ filesystem.compression_options | default(['none']) }}"