---
- name: "Filesystem Performance Tests"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    filesystems_to_test:
      - name: "ext4"
        block_sizes: [4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "xfs"
        block_sizes: [4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "btrfs"
        block_sizes: [4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "f2fs"
        block_sizes: [4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "zfs"
        block_sizes: [4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: false
    test_mount_point: "/mnt/test"
    results_base_path: "./wyniki"
  vars_files:
    - ./fio/fio_configs_vars.yaml
    - ./dd/dd_vars.yaml

  tasks:
    - name: Run tests for each filesystem and device
      include_tasks: perform_filesystem_tests.yaml
      loop: "{{ filesystems_to_test | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: filesystem