---
- name: "Filesystem Performance Tests"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    enabled_programs:
      - fio
      - hdparm
      - dd
      #- sysbench
      #- ab
      #- corpus
    filesystems_to_test:
      - name: "ext4"
        block_sizes: ["default"] #możliwe wartości: ["default",1024,2048,4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "xfs"
        block_sizes: ["default"]  #możliwe wartości: ["default",1024,2048,4096]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "btrfs"
        block_sizes: ["default"]  #możliwe wartości: ["default",4096,8192,16384,32768,65536]
        mount_opts: "defaults,noatime"
        snapshot_count: 0
        #compression_options: ["zstd:1", "zstd:3", "zstd:9", "zstd:15", "zlib:1", "zlib:3", "zlib:9"] #możliwe wartości: ["zstd", "lzo", "zlib", "none"]
        force_compress: false
        test_devices: ["hdd", "ssd", "nvme"] # możliwe wartości: ["hdd", "ssd", "nvme", "raid1", "raid04hdd", "raid02hdd", "raid5", "raid6", "raid10"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "f2fs"
        block_sizes: ["default"] 
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "zfs"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        arc_limit: false
        arc_reset: true
        snapshot_count: 0
        #compression_options: ["lz4","gzip-1","gzip-3","gzip-9"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        test_devices: ["hdd", "ssd", "nvme"]  # możliwe wartości: ["hdd", "ssd", "nvme", "mirror", "stripe2hdd", "stripe4hdd", "raidz1", "raidz2", "raidz3", "raid10"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "zfs_nocache"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        snapshot_count: 0
        #compression_options: ["lz4","gzip-1","gzip-3","gzip-9"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        test_devices: ["hdd", "ssd", "nvme"] # możliwe wartości: ["hdd", "ssd", "nvme", "mirror", "stripe2hdd", "stripe4hdd", "raidz1", "raidz2", "raidz3", "raid10"]
        direct_modes: ["0", "1"]
        enabled: true
      - name: "zfs_l2arc"
        block_sizes: ["default"]
        l2arc_device_short: "ssd"
        mount_opts: "defaults,noatime"
        arc_limit: false
        arc_reset: true
        snapshot_count: 0
        #compression_options: ["lz4","gzip-1","gzip-3","gzip-9"] #możliwe wartości: ["gzip","lz4","lzjb","zle","zstd","zstd-fast"]
        test_devices: ["hdd"] 
        direct_modes: ["0", "1"]
        enabled: true
      - name: "exfat"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        direct_modes: ["0"]
        enabled: true
    test_mount_point: "/mnt/test"
    results_base_path: "./wyniki"
    clear_caches: true
    snapshot_batch_size: 120
    bcache_enabled: false
  vars_files:
    - ./fio/fio_configs_vars.yaml #SPRAWDZIĆ PRZED ODPALENIEM
    - ./dd/dd_vars.yaml
    - ./sysbench/sysbench_configs_vars.yaml
    - ./ab/ab_configs_vars.yaml

  tasks:
    - name: Run tests for each filesystem and device
      include_tasks: perform_filesystem_tests.yaml
      loop: "{{ filesystems_to_test | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: filesystem
      vars:
        block_sizes: "{{ filesystem.block_sizes | default(['default']) }}"
        compression_options: "{{ filesystem.compression_options | default(['none']) }}"
        l2arc_device_short: "{{ filesystem.l2arc_device_short | default('none') }}"
        arc_limit: "{{ filesystem.arc_limit | default(false) }}"
        arc_reset: "{{ filesystem.arc_reset | default(false) }}"
        snapshot_count: "{{ filesystem.snapshot_count | default(0) }}"
        force_compress: "{{ filesystem.force_compress | default(false) }}"
        direct_modes: "{{ filesystem.direct_modes | default(['0']) }}"