---
- name: "Filesystem Performance Tests"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    filesystems_to_test:
      - name: "ext4"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "xfs"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "btrfs"
        block_sizes: ["default"]
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "f2fs"
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "zfs"
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: false
      - name: "zfs_nocache"
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
      - name: "exfat"
        mount_opts: "defaults,noatime"
        test_devices: ["hdd", "ssd", "nvme"]
        enabled: true
    test_mount_point: "/mnt/test"
    results_base_path: "./wyniki"
  vars_files:
    - ./fio/fio_configs_vars.yaml
    - ./dd/dd_vars.yaml

  tasks:
    - name: Ensure block_sizes is set to default if not defined
      set_fact:
        filesystems_to_test: >-
          {{
            filesystems_to_test | map(
              "combine", 
              {"block_sizes": ["default"]} if item.block_sizes is not defined else {}
            ) | list
          }}

    - name: Run tests for each filesystem and device
      include_tasks: perform_filesystem_tests.yaml
      loop: "{{ filesystems_to_test | selectattr('enabled', 'equalto', true) | list }}"
      loop_control:
        loop_var: filesystem