---
- name: Run tests for each block size
  include_tasks: perform_block_size_tests.yaml
  loop: "{{ block_sizes }}"
  loop_control:
    loop_var: block_size
  vars:
    create_opts: >-
      {% if filesystem_type == "ext4" and block_size != "default" %}
        -b {{ block_size }}
      {% elif filesystem_type == "xfs" and block_size != "default" %}
        -b size={{ block_size }}
      {% elif filesystem_type == "btrfs" and block_size != "default" %}
        -n {{ block_size }}
      {% elif filesystem_type == "f2fs" %}
        -f
      {% else %}
        ""
      {% endif %}
  when: 
    - test_device is defined
    - test_device | length > 0
    - test_device != "None"