---
- name: Print current device
  ansible.builtin.debug:
    msg: "Starting tests on device: {{ test_device_short }} for filesystem: {{ filesystem_type }}"

- name: Set test device
  set_fact:
    test_device: >-
      {{ 
        ("/dev/sda5" if test_device_short == "hdd" else
         "/dev/sdb1" if test_device_short == "ssd" else
         "/dev/nvme0n1p4" if test_device_short == "nvme" else
         fail("Invalid test_device_short value: " ~ test_device_short)) | trim 
      }}

- name: Run tests for each block size
  include_tasks: perform_block_size_tests.yaml
  loop: "{{ block_sizes }}"
  loop_control:
    loop_var: block_size
  vars:
    create_opts: >-
      {% if filesystem_type == "ext4" %}
        -b {{ block_size }}
      {% elif filesystem_type == "xfs" %}
        -b size={{ block_size }}
      {% elif filesystem_type == "btrfs" %}
        -n {{ block_size }}
      {% else %}
        ""
      {% endif %}