- name: Set test device
  set_fact:
    test_device: >-
      {{ 
        ("/dev/sda5" if test_device_short == "hdd" else
         "/dev/sdb1" if test_device_short == "ssd" and inventory_hostname in groups['ssd_hosts'] else
         "/dev/nvme0n1p4" if test_device_short == "nvme" else
         None) | trim 
      }}

- name: Set L2ARC device
  set_fact:
    l2arc_device: >-
      {{ 
        ("/dev/sdb1" if l2arc_device_short == "ssd" and inventory_hostname in groups['ssd_hosts'] else
         None) | trim 
      }}
  when:
    - filesystem_type == "zfs_l2arc"

- name: Skip task for unsupported devices
  ansible.builtin.debug:
    msg: "Skipping tests for device: {{ test_device_short }} on host: {{ inventory_hostname }}"
  when: 
    - test_device is not defined or test_device | length == 0 or test_device == "None"

- name: Run tests for compression options
  include_tasks: perform_compression_tests.yaml
  loop: "{{ compression_options }}"
  loop_control:
    loop_var: compression_option
