---
- name: Run tests for each raid
  include_tasks: perform_raid_tests.yaml
  loop: "{{ raid_options }}"
  loop_control:
    loop_var: raid_option
  vars:
    raid_opts: >-
      {% if filesystem_type == "btrfs" and inventory_hostname in groups['raid_hosts'] %}
        {% if raid_option == '0' %}
      -d raid0 -m raid0 /dev/sda /dev/sdb /dev/sdc /dev/sdd
        {% elif raid_option == '1' %}
      -d raid1 -m raid1 /dev/sda /dev/sdb
        {% elif raid_option == '5' %}
      -d raid5 -m raid1 /dev/sda /dev/sdb /dev/sdc
        {% elif raid_option == '6' %}
      -d raid6 -m raid1 /dev/sda /dev/sdb /dev/sdc /dev/sdd
        {% elif raid_option == '10' %}
      -d raid10 -m raid10 /dev/sda /dev/sdb /dev/sdc /dev/sdd
        {% endif %}
      {% endif %}
