---
- name: Install fio
  ansible.builtin.apt:
    name: fio
    state: present
  when: 
    - ansible_os_family == "Debian"
    - "'fio' in enabled_programs"

- name: Install f2fs-tools
  ansible.builtin.apt:
    name: f2fs-tools
    state: present
  when: ansible_os_family == "Debian" and filesystem_type == "f2fs"

- name: Install exfatprogs
  ansible.builtin.apt:
    name: exfatprogs
    state: present
  when: ansible_os_family == "Debian" and filesystem_type == "exfat"

- name: Unmount a mounted volume
  ansible.posix.mount:
    path: "{{ test_mount_point }}"
    state: unmounted 

- name: Delete bcache cache device
  include_tasks: bcache/delete_bcache.yaml

- name: Destroy ZFS filesystem and pool
  block:
    - name: Unmount ZFS filesystem
      shell: zfs unmount mypool/myfilesystem
      ignore_errors: true

    - name: Destroy ZFS filesystem
      shell: zfs destroy mypool/myfilesystem
      ignore_errors: true

    - name: Destroy ZFS pool
      shell: zpool destroy mypool
      ignore_errors: true

- name: Blank filesystem on the RAID devices
  shell: "wipefs -af {{ item }}"
  loop:
    - /dev/sda
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd
  when: raid_opts is defined

- name: Blank filesystem on the device
  shell: "wipefs -af {{ test_device }}"
  when: raid_opts is not defined

- name: Clear Linux caches (PageCache, dentries, inodes) before test
  ansible.builtin.shell: "echo 3 > /proc/sys/vm/drop_caches"
  changed_when: false
  when: clear_caches is defined and clear_caches
