---
- name: "EXT4 Performance Test with FIO"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    test_device: "/dev/sda5"
    test_device_short: "hdd"
    test_mount_point: "/mnt/test"
    dd_tests:
      - name: "dd_write_test"
        bs: "1M"
        count: 1024
        oflag: "direct"
        if: "/dev/zero"
        of: "{{ test_mount_point }}/testfile"
      - name: "dd_read_test"
        bs: "1M"
        count: 1024
        iflag: "direct"
        if: "{{ test_mount_point }}/testfile"
        of: "/dev/null"
  vars_files:
    - fio_configs_vars.yaml
    
  tasks:
    - import_tasks: prepare_tasks.yaml

    - name: Create EXT4 filesystem with specified block size
      community.general.filesystem:
        fstype: ext4
        dev: "{{ test_device }}"
        opts: "-b {{ block_size }}"

    - name: Mount the device to the test mount point
      ansible.posix.mount:
        path: "{{ test_mount_point }}"
        src: "{{ test_device }}"
        fstype: ext4
        opts: "defaults,noatime"
        state: mounted

    - import_tasks: fio_run.yaml

    - import_tasks: dd_tests.yaml

    - name: Gather FIO results
      ansible.builtin.fetch:
        src: "/tmp/fio_{{ item }}_output.txt"
        dest: "./fio_results_ext4_{{ test_device_short }}/{{ inventory_hostname }}/"
        flat: yes
      loop:
        - database_test
        - multimedia_test
        - webserver_test
        - archive_test
