---
- name: "EXT4 Performance Test with FIO"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    test_device: "/dev/sda5"
    test_device_short: "hdd"
    test_mount_point: "/mnt/test"
    filesystem_type: "ext4"  # Added this line
    
    timestamp: "{{ ansible_date_time.iso8601_basic }}"
    dd_results_path: "./{{ timestamp }}_dd_results_{{ filesystem_type }}_{{ test_device_short }}/{{ inventory_hostname }}/"
    fio_results_path: "./{{ timestamp }}_fio_results_{{ filesystem_type }}_{{ test_device_short }}/{{ inventory_hostname }}/"
  vars_files:
    - fio_configs_vars.yaml
    
  tasks:
    - import_tasks: prepare_tasks.yaml

    - name: Create EXT4 filesystem with specified block size
      community.general.filesystem:
        fstype: ext4
        dev: "{{ test_device }}"
        opts: "-b {{ block_size }}"

    - name: Mount the device to the test mount point
      ansible.posix.mount:
        path: "{{ test_mount_point }}"
        src: "{{ test_device }}"
        fstype: ext4
        opts: "defaults,noatime"
        state: mounted


    - import_tasks: dd_tests.yaml

    - import_tasks: fio_run.yaml

    - name: Gather FIO results
      ansible.builtin.fetch:
        src: "/tmp/fio_{{ item }}_output.txt"
        dest: "{{ fio_results_path }}"
        flat: yes
      loop:
        - database_test
        - multimedia_test
        - webserver_test
        - archive_test

    - name: Save FIO configuration to results folder
      ansible.builtin.copy:
        content: |
          Test Device: {{ test_device }}
          Test Mount Point: {{ test_mount_point }}
          Filesystem Type: {{ filesystem_type }}
        dest: "{{ fio_results_path }}/fio_config.txt"