---
- name: "ZFS Performance Test with FIO"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    test_device: "/dev/sda5"
    test_device_short: "sda"
    test_mount_point: "/mnt/test"
  vars_files:
    - fio_configs_vars.yaml
    
  tasks:
    - import_tasks: prepare_tasks.yaml
    
    - name: Utwórz pulę ZFS na /dev/sda5
      command: zpool create mypool {{ test_device }}
      args:
        creates: /mypool

    - name: Utwórz system plików ZFS w puli
      command: zfs create mypool/myfilesystem
      args:
        creates: /mypool/myfilesystem

    - name: Ustaw punkt montowania systemu plików ZFS
      command: zfs set mountpoint={{ test_mount_point }} mypool/myfilesystem
    
    - name: Mount DVD read-only
      ansible.posix.mount:
        path: "{{ test_mount_point }}"
        src: "{{ test_device }}"
        fstype: zfs
        opts: "defaults,noatime"
        state: mounted

    - import_tasks: fio_run.yaml


    - name: Usuń system plików ZFS
      block:
        - name: Odmontuj system plików ZFS
          command: zfs unmount mypool/myfilesystem
          ignore_errors: true

        - name: Usuń system plików ZFS
          command: zfs destroy mypool/myfilesystem
          ignore_errors: true

        - name: Usuń pulę ZFS
          command: zpool destroy mypool
          ignore_errors: true

    - name: Gather FIO results
      ansible.builtin.fetch:
        src: "/tmp/fio_{{ item }}_output.txt"
        dest: "./fio_results_zfs_{{ test_device_short }}/{{ inventory_hostname }}/"
        flat: yes
      loop:
        - database_test
        - multimedia_test
        - webserver_test
        - archive_test


